###############################
# topic-viz.py 
# A script for generating a static HTML site for analyzing the output of topic models generated by nPLSA
#
#
#
#
###############################

import os
import re
import sys
import json


dataDirectory = "./data"
htmlDirectory = "./html"



try:
	filelist = [f for f in os.listdir(dataDirectory) if f.startswith('nplsa.topicSize.') and f[-1].isdigit()]
	iterations = max([int(re.sub("\D", "", f)) for f in filelist])
	with open(dataDirectory + "nplsa.topicSize." + str(iterations)) as file:
   		numTopics = len(file.readlines())
except:
	print("""
There is something wrong with your data directory. 
It should contain a number of files named 'nplsa.topicsize.NUM'
Take a look in ./data and make sure the files are there.
		""")
	sys.exit()

print("Building data files for Topic Size visualization.")

series = [{"key":str(num), "values":[]} for num in range(0,numTopics)]  # set up the data structure for the d3.js visualization

for filename in filelist:
	try:
		with open(iterationsDirectory + str(filename)) as file:
			content = [float(line.strip()) for line in file]
			line = content + ([0] * (numTopics - len(content)))
			for topic, value in enumerate(line):
				series[int(topic)]["values"].append({"x":num, "y":float(value)})
	except Exception, e:
		print(e)


print("Writing topic size JSON files to HTML directory.")

with open(htmlDirectory+"/meta.json", 'w') as metaJson:
	metaJson.write(json.dumps({"iterations":iterations, "numtopics":numTopics}))

with open(htmlDirectory+"/topicSize.json",'w') as filey:
	filey.write(json.dumps(series))



